[package]
name = "interledger-settlement"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Settlement-related components for Interledger.rs"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/emschwartz/interledger-rs"

[dependencies]
bytes = "0.4.12"
futures = "0.1.25"
hyper = "0.12.29"
interledger-packet = { path = "../interledger-packet", version = "0.2.1" }
interledger-service = { path = "../interledger-service", version = "0.2.1" }
interledger-ildcp = { path = "../interledger-ildcp", version = "0.2.1" }
log = "0.4.6"
reqwest = "0.9.17"
serde = "1.0.91"
serde_json = "1.0.39"
tower-web = "0.3.7"
url = "1.7.2"
lazy_static = "1.3.0"
uuid = "0.7.4"
rand = "0.6.5"
ring = "0.14.6"
tokio-retry = "0.2.0"
tokio = "0.1.20"
num-bigint = "0.2.2"
num-traits = "0.2.8"

[dev-dependencies]
parking_lot = "0.8.0"
mockito = "0.17.1"
env_logger = "0.6.1"
